server:
  port: 8080 #用户微服务端口
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:9080/eureka/,http://127.0.0.1:8090/eureka/
spring:
  datasource:
    username: root
    password: root
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    druid:
      filters: stat,wall,slf4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  rabbitmq:
    host: 47.102.111.104
    port: 5672
    username: admin
    password: admin
  application:
    name: user-service  #微服务名称
  cloud:
    stream:
      bindings:
        output:
          destination: trade
          contentType: 'application/json'
    config:
#      uri: http://localhost:7001/
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
      profile: test
feign:
  hystrix:
    enabled: true  # 开启服务降级功能  必须开启否则会报错而且调用不了降级方法
management:
  endpoint:
    env:
      enabled: true
    web:
      exposure:
        include: '*'

